# Test Configuration for Security Pipeline Validation
# This file tests YAML validation and workflow triggers

version: "1.0"
test_scenarios:
  security_scanning:
    enabled: true
    severity_levels:
      - critical
      - high
      - medium
    tools:
      - trivy
      - trufflehog
      - safety
      
  branch_protection:
    enabled: true
    rules:
      - require_pull_request_reviews: true
      - require_code_owner_reviews: true
      - enforce_admins: true
      - required_linear_history: true
      
  workflow_validation:
    ci_checks:
      - validate-changes
      - security-analysis
      - quality-checks
      - documentation-check
    security_checks:
      - trivy-scan
      - secret-scan
      - compliance-check
      
  hook_system:
    auto_delegate: true
    pre_commit_review: true
    agents:
      - qa-testing-specialist
      - security-compliance-auditor
      - sre-devops-specialist
      - frontend-developer
      - backend-developer
      - product-requirements-analyst

# Test data for validation
test_credentials:
  # These are safe test patterns for secret scanner validation
  fake_api_key: "test_key_placeholder_not_real_12345"
  demo_password: "example_password_for_testing_only"
  sample_token: "demo_token_validation_purposes_67890"
  
quality_standards:
  accessibility: "WCAG 2.1 AA"
  test_coverage: "90%"
  security_scan: "zero_high_critical"
  uptime_slo: "99.9%"
  
monitoring:
  alerts_enabled: true
  log_retention_days: 30
  security_events: true