name: 🐛 Bug Report
description: Report a bug in the claude-code-sub-agents ecosystem
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the following information to help us resolve the issue.

  - type: dropdown
    id: affected-agent
    attributes:
      label: Affected Agent
      description: Which sub-agent is experiencing the issue?
      options:
        - product-requirements-analyst
        - frontend-developer
        - backend-developer
        - sre-devops-specialist
        - qa-testing-specialist
        - security-compliance-auditor
        - pre-commit-reviewer
        - auto-delegation system
        - hook scripts
        - settings configuration
        - other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - OS: [e.g. macOS 13.0, Ubuntu 22.04]
        - Claude Code Version: [e.g. v1.2.3]
        - Agent Version: [e.g. v2.1.0]
        - Shell: [e.g. bash, zsh]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have run `./validate-setup.sh` to ensure my configuration is valid
          required: true
        - label: This issue affects the sub-agent ecosystem functionality
          required: true